import { Metadata } from 'next'
import './globals.css'
import { Suspense } from 'react'
export const metadata: Metadata = {
  title: {
    default: 'Next.js',
    template: '%s - Next.js',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='bg-blue-400 p-4'>
          <p>Header</p>
        </header>
        <Suspense>{children}</Suspense>

        <footer className='bg-gray-300 p-4'>
          <p>footer</p>
        </footer>
      </body>
    </html>
  )
}
